% Matrices, Vectors

clc, clearvars, close all
load("data.mat")

numbers = [Politics, Technology, World, Sports];
biggest = 0;
for i = 1:length(numbers)
    if numbers(i) > biggest
        biggest = numbers(i);
    end
end
figure(1);
bar(numbers, 0.3, "green")
xlabel('Category'); 
ylabel('Number of Headlines'); 
title('CNN NEWS HEADLINES','Units','normalized','Position',[0.5 1.05 0])
labels = ["Politics" "Technology" "World", "Sports"];

x = 1:numel(numbers);    % x‑positions of bars

for i = 1:numel(numbers)
    text(x(i), numbers(i), labels(i), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom')
end

figure(2)
axis off   % removes axes
%title("Stats")
spacing = 1;
text(0.5, 1, "Sampled Headlines", ...
    'Units','normalized', ...
    'HorizontalAlignment','center', ...
    'FontSize',15)
headlineLength = size(headlines,1);
for i = 1:headlineLength
    text(0, 1 - spacing*i/(headlineLength+1), headlines(i, :), ...
    'Units','normalized', ...
    'HorizontalAlignment','left', ...
    'FontSize',10)
end

figure(3)
axis off
text(0, 1, "Most Trending Category", ...
    'Units','normalized', ...
    'HorizontalAlignment','left', ...
    'FontSize',15)
% Display the most trending category based on the biggest value
mostTrendingCategory = labels(find(numbers == biggest, 1));
text(0, 0.5, mostTrendingCategory, ...
    'Units','normalized', ...
    'HorizontalAlignment','left', ...
    'FontSize',12, ...
    'Color','red');

text(1, 1, "Model Accuracy (%)", ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'FontSize',15)
text(1, 0.5, string(accuracy), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'FontSize',12, ...
    'Color','red');

